// 국가코드표 — reference lookup for productionCountry / madeCountryCode fields
// used by product create/update endpoints. Sourced from vendor Notion docs.
export const COUNTRY_CODES: Record<string, string> = {
  AX: "ALAND ISLANDS",
  AD: "ANDORRA",
  AU: "AUSTRALIA",
  AT: "AUSTRIA",
  BH: "BAHRAIN",
  BE: "BELGIUM",
  BZ: "BELIZE",
  BR: "BRAZIL",
  BN: "BRUNEI DARUSSALAM",
  BG: "BULGARIA",
  CA: "CANADA",
  E2: "E2",
  CL: "CHILE",
  CN: "CHINA",
  CO: "COLOMBIA",
  CR: "COSTARICA",
  CY: "CYPRUS",
  CZ: "CZECHREP",
  DK: "DENMARK",
  EC: "ECUADOR",
  EG: "EGYPT",
  SV: "ELSALVADOR",
  EE: "ESTONIA",
  FR: "FRANCE",
  GF: "FRENCHGUIANA",
  DE: "GERMANY",
  GR: "GREECE",
  GL: "GREENLAND",
  GU: "GUAM",
  GT: "GUATEMALA",
  GG: "GUERNSEY",
  GY: "GUYANA",
  HK: "HONGKONG",
  HU: "HUNGARY",
  IS: "ICELAND",
  ID: "INDONESIA",
  IE: "IRELAND",
  IL: "ISRAEL",
  IT: "ITALY",
  JP: "JAPAN",
  JE: "BAILIWICK OF JERSEY",
  JO: "JORDAN",
  KR: "KOREA REPUPLIC",
  KW: "KUWAIT",
  LV: "LATVIA",
  LB: "LEBANON",
  LI: "LIECHTENSTEIN",
  LT: "LITHUANIA",
  LU: "LUXEMBOURE",
  MO: "MACAO",
  P2: "P2",
  MY: "MALAYSIA",
  NL: "NETHERLANDS",
  NZ: "NEWZEALAND",
  G2: "G2",
  NO: "NORWAY",
  PY: "PARAGUAY",
  PE: "PERU",
  PL: "POLAND",
  PT: "PORTUGAL",
  RO: "ROMANIA",
  RU: "RUSSIAN FEDERATION",
  SM: "SANMARINO",
  SA: "SAUDIARABIA",
  G3: "G3",
  SG: "SINGAPORE",
  SK: "SLOVAKIA",
  SI: "SLOVENIA",
  ES: "SPAIN",
  CH: "SWITZERLAND",
  TW: "TAIWAN",
  TH: "THAILAND",
  TR: "TURKEY",
  AE: "UNITED ARABEMIRATES",
  GB: "UNITED KINGDOM",
  US: "USA",
  U2: "U2",
  UY: "URUGUAY",
  VN: "VIETNAM",
  G4: "G4",
  YE: "YEMEN",
  HR: "CROATIA",
  MT: "MALTA",
  FI: "FINLAND",
  SE: "SWEDEN",
};
